logLevel: info
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 1024

authMethod: internal
authInternalUsers:
  - user: media-api
    pass: replace-with-media-api-password
    ips: []
    permissions:
      - action: api
        path:
  - user: any
    pass:
    ips: []
    permissions:
      - action: read
        path: "~^SB_[^/]+$"

api: true
apiAddress: :9997
metrics: false
pprof: false
playback: false

rtsp: true
rtspTransports: [tcp]
rtspEncryption: "no"
rtspAddress: :8554
rtspAuthMethods: [digest]

rtmp: false
hls: false
srt: false
moq: false

webrtc: true
webrtcAddress: :8889
webrtcEncryption: false
webrtcLocalUDPAddress: :19091
webrtcLocalTCPAddress: ""
webrtcAdditionalHosts: []

pathDefaults:
  source: publisher
  overridePublisher: false
  record: false

paths:
  "~^ingest/SB_[^/]+$": {}
  "~^SB_[^/]+$": {}
